### ISSUE TITLE
Unicode-escape 

### ISSUE THREAD

**Issue by Guiforge** [mguillau42/unit_test_nm_otool#2]
When the programme use ASCII sequence
Traceback:
```
Traceback (most recent call last):
  File "unit_test.py", line 203, in <module>
    sys.exit(tests_main(args))
  File "unit_test.py", line 135, in tests_main
    errors += tests_nm(files_to_test, args)
  File "unit_test.py", line 45, in tests_nm
    out , rc , err = execute("{} {}".format(NM_PATH, t))
  File "unit_test.py", line 19, in execute
    output = output.decode().rstrip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2200: invalid start byte
```

**Comment by chaource** [comment]
Sorry for the late reply, I almost forgot this project. Thanks again for the pull request !
